#!/bin/bash
# runParameterSweep.sh
#
# Generate and run an oscillating-film parameter sweep using SWEEP_* definitions.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARSER_HELPER="${SCRIPT_DIR}/src-local/parse_params.sh"

usage() {
  cat <<'EOF_USAGE'
Usage: bash runParameterSweep.sh [sweep_file] [--exec exec_code] [OPTIONS]

Arguments:
  sweep_file Sweep configuration file (default: sweep.params)

Options:
  --exec FILE   C source file in simulationCases/ (default: oscillatingFilm.c)
  --mpi         Run generated cases in MPI mode
  --CPUs N      MPI process count for --mpi (default: 4)
  --dry-run     Generate and validate cases, but do not execute
  -h, --help    Show this help message

Sweep file format:
  BASE_CONFIG=default.params
  CASE_START=1000
  CASE_END=1003
  SWEEP_Ohf=1e-2,5e-2
  SWEEP_amp=5e-2,1e-1
EOF_USAGE
}

if [[ ! -f "$PARSER_HELPER" ]]; then
  echo "ERROR: Shared parser helper not found: $PARSER_HELPER" >&2
  exit 1
fi
# shellcheck disable=SC1090
source "$PARSER_HELPER"

SWEEP_FILE="sweep.params"
SWEEP_FILE_SET=0
EXEC_CODE="oscillatingFilm.c"
USE_MPI=0
MPI_CPUS=4
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --exec)
      if [[ -z "${2:-}" ]]; then
        echo "ERROR: --exec requires a file name." >&2
        usage
        exit 1
      fi
      EXEC_CODE="$2"
      shift 2
      ;;
    --exec=*)
      EXEC_CODE="${1#*=}"
      shift
      ;;
    --mpi)
      USE_MPI=1
      shift
      ;;
    --CPUs|--cpus)
      if [[ -z "${2:-}" ]]; then
        echo "ERROR: $1 requires a positive integer value." >&2
        usage
        exit 1
      fi
      MPI_CPUS="$2"
      shift 2
      ;;
    --CPUs=*|--cpus=*)
      MPI_CPUS="${1#*=}"
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      echo "ERROR: Unknown option: $1" >&2
      usage
      exit 1
      ;;
    *)
      if [[ $SWEEP_FILE_SET -eq 0 ]]; then
        SWEEP_FILE="$1"
        SWEEP_FILE_SET=1
        shift
      else
        echo "ERROR: Unexpected argument: $1" >&2
        usage
        exit 1
      fi
      ;;
  esac
done

if [[ $# -gt 0 ]]; then
  echo "ERROR: Unexpected trailing arguments: $*" >&2
  usage
  exit 1
fi

if [[ ! "$MPI_CPUS" =~ ^[1-9][0-9]*$ ]]; then
  echo "ERROR: --CPUs must be a positive integer, got: $MPI_CPUS" >&2
  exit 1
fi

if [[ "$EXEC_CODE" != *.c ]]; then
  EXEC_CODE="${EXEC_CODE}.c"
fi

if [[ ! "$SWEEP_FILE" = /* ]]; then
  SWEEP_FILE="${SCRIPT_DIR}/${SWEEP_FILE}"
fi
if [[ ! -f "$SWEEP_FILE" ]]; then
  echo "ERROR: Sweep file not found: $SWEEP_FILE" >&2
  exit 1
fi

TMP_SWEEP_DIR=""
cleanup() {
  if [[ -n "$TMP_SWEEP_DIR" && -d "$TMP_SWEEP_DIR" ]]; then
    rm -rf "$TMP_SWEEP_DIR"
  fi
}
trap cleanup EXIT

TMP_SWEEP_DIR="$(generate_sweep_cases "$SWEEP_FILE")"
CASES_LIST="${TMP_SWEEP_DIR}/cases.list"
if [[ ! -f "$CASES_LIST" ]]; then
  echo "ERROR: cases.list not generated by sweep helper." >&2
  exit 1
fi

CASE_FILES=()
while IFS= read -r case_file || [[ -n "$case_file" ]]; do
  [[ -n "$case_file" ]] || continue
  CASE_FILES+=("$case_file")
done < "$CASES_LIST"

if [[ ${#CASE_FILES[@]} -eq 0 ]]; then
  echo "ERROR: No case parameter files were generated from sweep: $SWEEP_FILE" >&2
  exit 1
fi

CASE_NUMBERS=()
for case_file in "${CASE_FILES[@]}"; do
  if ! parse_param_file "$case_file"; then
    echo "ERROR: Failed to parse generated case file: $case_file" >&2
    exit 1
  fi
  case_no="$(get_param "CaseNo")"
  if [[ -z "$case_no" || ! "$case_no" =~ ^[0-9]+$ ]]; then
    echo "ERROR: Generated case has invalid CaseNo: $case_file" >&2
    exit 1
  fi
  CASE_NUMBERS+=("$case_no")
done

expected="${CASE_NUMBERS[0]}"
for case_no in "${CASE_NUMBERS[@]}"; do
  if [[ "$case_no" -ne "$expected" ]]; then
    echo "ERROR: Non-deterministic CaseNo sequence in generated sweep cases." >&2
    echo "       expected ${expected}, got ${case_no}" >&2
    exit 1
  fi
  expected=$((expected + 1))
done

last_index=$((${#CASE_NUMBERS[@]} - 1))
case_start="${CASE_NUMBERS[0]}"
case_end="${CASE_NUMBERS[$last_index]}"

echo "========================================="
echo "Oscillating Film - Parameter Sweep Runner"
echo "========================================="
echo "Sweep file: ${SWEEP_FILE}"
echo "Source file: ${EXEC_CODE}"
echo "Generated cases: ${#CASE_FILES[@]}"
echo "CaseNo range: ${case_start}..${case_end}"
if [[ $USE_MPI -eq 1 ]]; then
  echo "Run mode: MPI (np=${MPI_CPUS})"
else
  echo "Run mode: Serial"
fi
if [[ $DRY_RUN -eq 1 ]]; then
  echo "Execution mode: Dry run (no simulations launched)"
else
  echo "Execution mode: Run all cases"
fi
echo "========================================="

for idx in "${!CASE_FILES[@]}"; do
  printf '  [%03d] CaseNo=%s params=%s\n' \
    "$((idx + 1))" "${CASE_NUMBERS[$idx]}" "${CASE_FILES[$idx]}"
done

if [[ $DRY_RUN -eq 1 ]]; then
  exit 0
fi

RUN_ARGS=(--exec "$EXEC_CODE")
if [[ $USE_MPI -eq 1 ]]; then
  RUN_ARGS+=(--mpi --CPUs "$MPI_CPUS")
fi

failures=0
for idx in "${!CASE_FILES[@]}"; do
  case_file="${CASE_FILES[$idx]}"
  case_no="${CASE_NUMBERS[$idx]}"
  echo ""
  echo "Running case ${case_no} ($((idx + 1))/${#CASE_FILES[@]}) ..."
  if ! bash "${SCRIPT_DIR}/runSimulation.sh" "$case_file" "${RUN_ARGS[@]}"; then
    echo "ERROR: Case ${case_no} failed." >&2
    failures=$((failures + 1))
  fi
done

if [[ $failures -gt 0 ]]; then
  echo "Sweep completed with ${failures} failed case(s)." >&2
  exit 1
fi

echo ""
echo "Sweep completed successfully (${#CASE_FILES[@]} cases)."
